### ISSUE TITLE
2.2.1

### ISSUE THREAD

**Issue by DidenkoAndre** [mkuznets/quantum-mechanics-lectures#17]
Я точно помню, что написанное равенство (2.2.1) точно так же, как в книге признавалось Гецом на тесте неверным в том семестре.

Действительно, как оператор может быть равен числу. 

Требую исправить на то, что действительно в лекциях Суханова написано. 

Если я найду тетрадь лекций Суханова, то я даже, наверное, скажу, что там было написано...

**Comment by DidenkoAndre** [comment]
нашел, см #18

**Comment by mkuznets** [comment]
Огонь, спасибо!
